### ISSUE TITLE
retinanet.ipynb

### ISSUE THREAD

**Issue by ilyanelken** [keras-team/keras-io#162]
Hi,

Thanks for this great example.
A small question:

Does "padded_shapes" argument missing in "Setting up a tf.data pipeline" section in "train_dataset.padded_batch()" routine?

Thanks,
Ilya

**Comment by srihari-humbarwadi** [comment]
From the documentation of [padded_batch](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#padded_batch), the `padded_shapes` argument,  "If unset, all dimensions of all components are padded to the maximum size in the batch"
This is exactly what is need in the example, hence its left to its default value which happens to be `None`

**Comment by ilyanelken** [comment]
That what I would expect as well, but I get this error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-122a3597515e> in <module>
      3 train_dataset = train_dataset.shuffle(8 * batch_size)
      4 train_dataset = train_dataset.padded_batch(
----> 5     batch_size=batch_size, padding_values=(0.0, 1e-8, -1), drop_remainder=True
      6 )
      7 train_dataset = train_dataset.map(

TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'

**Comment by ilyanelken** [comment]
What TF version should I have?

**Comment by srihari-humbarwadi** [comment]
This example should work fine with tf-2.2 and later versions, which version are you using?

**Comment by ilyanelken** [comment]
So I guess that is the issue, I am currently working with TF 1.15 :(
