### ISSUE TITLE
Time series example is broken

### ISSUE THREAD

**Issue by markrogersjr** [keras-team/keras-io#589]
If I run `timeseries_weather_forecasting.py` with the latest version of Keras, I get the following error:
```
AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'timeseries_dataset_from_array'
```

**Comment by LanceNorskog** [comment]
Just now tested. It works in tf==2.5.0 and tf==2.6.0-rc1.
Did not test installing a keras version and whatever TF it includes.

**Comment by SuryanarayanaY** [comment]
Hi @markrogersjr ,

The example tutorial working fine now. Please refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/4ded817d41a21339421ef9fc97d40c95/kerasio_589-timeseries_weather_forecasting.ipynb).

Please cross check and close the issue if found resolved else let us know if any issue still there.

Thanks!
